# Generated by Django 5.2.6 on 2025-10-07 00:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('notification_type', models.CharField(choices=[('job_alert', "Alerte d'emploi"), ('application_update', 'Mise à jour de candidature'), ('message_received', 'Message reçu'), ('profile_reminder', 'Rappel de profil'), ('achievement', 'Réussite'), ('badge_earned', 'Badge obtenu'), ('level_up', 'Montée de niveau'), ('referral', 'Parrainage'), ('system', 'Système'), ('marketing', 'Marketing')], max_length=30, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Corps du message')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icône')),
                ('image_url', models.URLField(blank=True, verbose_name="URL de l'image")),
                ('action_url', models.URLField(blank=True, verbose_name="URL d'action")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Modèle de notification',
                'verbose_name_plural': 'Modèles de notifications',
                'ordering': ['notification_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, verbose_name="ID de l'appareil")),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS'), ('desktop', 'Desktop')], max_length=20, verbose_name="Type d'appareil")),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name="Nom de l'appareil")),
                ('push_token', models.TextField(verbose_name='Token de notification push')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Dernière vue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Appareil',
                'verbose_name_plural': 'Appareils',
                'ordering': ['-last_seen'],
                'unique_together': {('user', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='NotificationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('total_sent', models.PositiveIntegerField(default=0, verbose_name='Total envoyé')),
                ('total_delivered', models.PositiveIntegerField(default=0, verbose_name='Total livré')),
                ('total_opened', models.PositiveIntegerField(default=0, verbose_name='Total ouvert')),
                ('total_failed', models.PositiveIntegerField(default=0, verbose_name='Total échoué')),
                ('delivery_rate', models.FloatField(default=0.0, verbose_name='Taux de livraison (%)')),
                ('open_rate', models.FloatField(default=0.0, verbose_name="Taux d'ouverture (%)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Analyse de notification',
                'verbose_name_plural': 'Analyses de notifications',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Notifications push activées')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Notifications email activées')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='Notifications SMS activées')),
                ('job_alerts', models.BooleanField(default=True, verbose_name="Alertes d'emploi")),
                ('application_updates', models.BooleanField(default=True, verbose_name='Mises à jour de candidature')),
                ('messages', models.BooleanField(default=True, verbose_name='Messages')),
                ('profile_reminders', models.BooleanField(default=True, verbose_name='Rappels de profil')),
                ('achievements', models.BooleanField(default=True, verbose_name='Réussites')),
                ('badges', models.BooleanField(default=True, verbose_name='Badges')),
                ('level_ups', models.BooleanField(default=True, verbose_name='Montées de niveau')),
                ('referrals', models.BooleanField(default=True, verbose_name='Parrainages')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='Notifications système')),
                ('marketing', models.BooleanField(default=False, verbose_name='Marketing')),
                ('frequency', models.CharField(choices=[('instant', 'Instantané'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('never', 'Jamais')], default='instant', max_length=20, verbose_name='Fréquence')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Début des heures silencieuses')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Fin des heures silencieuses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normal'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priorité')),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Planifié le')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Tentatives max')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_notifications', to='push_notifications.notificationtemplate', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': "Notification en file d'attente",
                'verbose_name_plural': "Notifications en file d'attente",
                'ordering': ['priority', 'scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('campaign_type', models.CharField(choices=[('broadcast', 'Diffusion générale'), ('targeted', 'Ciblée'), ('scheduled', 'Planifiée'), ('triggered', 'Déclenchée')], max_length=20, verbose_name='Type de campagne')),
                ('target_filters', models.JSONField(blank=True, default=dict, verbose_name='Filtres de ciblage')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Planifié le')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Envoyée')),
                ('total_sent', models.PositiveIntegerField(default=0, verbose_name='Total envoyé')),
                ('total_delivered', models.PositiveIntegerField(default=0, verbose_name='Total livré')),
                ('total_opened', models.PositiveIntegerField(default=0, verbose_name='Total ouvert')),
                ('total_failed', models.PositiveIntegerField(default=0, verbose_name='Total échoué')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('target_users', models.ManyToManyField(blank=True, related_name='notification_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs ciblés')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='push_notifications.notificationtemplate', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': 'Campagne de notification',
                'verbose_name_plural': 'Campagnes de notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Corps du message')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icône')),
                ('image_url', models.URLField(blank=True, verbose_name="URL de l'image")),
                ('action_url', models.URLField(blank=True, verbose_name="URL d'action")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('delivered', 'Livrée'), ('opened', 'Ouverte'), ('failed', 'Échouée')], default='pending', max_length=20, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Livré le')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Ouvert le')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='push_notifications.device', verbose_name='Appareil')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='push_notifications.notificationtemplate', verbose_name='Modèle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification push',
                'verbose_name_plural': 'Notifications push',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(max_length=50, verbose_name="Type d'abonnement")),
                ('subscription_data', models.JSONField(blank=True, default=dict, verbose_name="Données d'abonnement")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Abonné le')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Désabonné le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement aux notifications',
                'verbose_name_plural': 'Abonnements aux notifications',
                'ordering': ['-subscribed_at'],
                'unique_together': {('user', 'subscription_type')},
            },
        ),
    ]
