# Generated by Django 5.2.6 on 2025-10-06 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du programme')),
                ('description', models.TextField(verbose_name='Description')),
                ('referrer_reward', models.JSONField(default=dict, verbose_name='Récompense du parrain')),
                ('referee_reward', models.JSONField(default=dict, verbose_name='Récompense du filleul')),
                ('min_referrals_for_bonus', models.PositiveIntegerField(default=5, verbose_name='Minimum de parrainages pour bonus')),
                ('bonus_reward', models.JSONField(default=dict, verbose_name='Récompense bonus')),
                ('max_referrals_per_user', models.PositiveIntegerField(default=10, verbose_name='Maximum de parrainages par utilisateur')),
                ('max_rewards_per_user', models.PositiveIntegerField(default=1000, verbose_name='Maximum de récompenses par utilisateur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Programme de recommandation',
                'verbose_name_plural': 'Programmes de recommandation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code de recommandation')),
                ('total_uses', models.PositiveIntegerField(default=0, verbose_name="Nombre total d'utilisations")),
                ('successful_referrals', models.PositiveIntegerField(default=0, verbose_name='Parrainages réussis')),
                ('total_rewards_earned', models.PositiveIntegerField(default=0, verbose_name='Total des récompenses gagnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to='referrals.referralprogram', verbose_name='Programme')),
            ],
            options={
                'verbose_name': 'Code de recommandation',
                'verbose_name_plural': 'Codes de recommandation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email invité')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'invité")),
                ('message', models.TextField(blank=True, verbose_name='Message personnalisé')),
                ('status', models.CharField(choices=[('sent', 'Envoyée'), ('opened', 'Ouverte'), ('clicked', 'Cliquée'), ('registered', 'Inscrite'), ('expired', 'Expirée')], default='sent', max_length=20, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyée le')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Ouverte le')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Cliquée le')),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Inscrite le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='referrals.referralcode', verbose_name='Code de recommandation')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Parrain')),
            ],
            options={
                'verbose_name': 'Invitation de recommandation',
                'verbose_name_plural': 'Invitations de recommandation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='pending', max_length=20, verbose_name='Statut')),
                ('referrer_reward_given', models.BooleanField(default=False, verbose_name='Récompense parrain donnée')),
                ('referee_reward_given', models.BooleanField(default=False, verbose_name='Récompense filleul donnée')),
                ('referrer_reward_amount', models.PositiveIntegerField(default=0, verbose_name='Montant récompense parrain')),
                ('referee_reward_amount', models.PositiveIntegerField(default=0, verbose_name='Montant récompense filleul')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL, verbose_name='Filleul')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='Parrain')),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.referralcode', verbose_name='Code de recommandation')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.referralprogram', verbose_name='Programme')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['-created_at'],
                'unique_together': {('referrer', 'referee', 'program')},
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('points', 'Points'), ('credits', 'Crédits'), ('discount', 'Remise'), ('premium_access', 'Accès premium'), ('badge', 'Badge'), ('cash', 'Argent')], max_length=20, verbose_name='Type de récompense')),
                ('amount', models.PositiveIntegerField(verbose_name='Montant')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='Réclamée')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Réclamée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='referrals.referral', verbose_name='Recommandation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Récompense de recommandation',
                'verbose_name_plural': 'Récompenses de recommandation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_referrals', models.PositiveIntegerField(default=0, verbose_name='Total des recommandations')),
                ('successful_referrals', models.PositiveIntegerField(default=0, verbose_name='Recommandations réussies')),
                ('total_rewards', models.PositiveIntegerField(default=0, verbose_name='Total des récompenses')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='Rang')),
                ('period_start', models.DateTimeField(verbose_name='Début de période')),
                ('period_end', models.DateTimeField(verbose_name='Fin de période')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_leaderboard', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='referrals.referralprogram', verbose_name='Programme')),
            ],
            options={
                'verbose_name': 'Classement de recommandation',
                'verbose_name_plural': 'Classements de recommandation',
                'ordering': ['rank', '-total_referrals'],
                'unique_together': {('user', 'program', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='ReferralAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('total_invitations_sent', models.PositiveIntegerField(default=0, verbose_name='Total invitations envoyées')),
                ('total_invitations_opened', models.PositiveIntegerField(default=0, verbose_name='Total invitations ouvertes')),
                ('total_invitations_clicked', models.PositiveIntegerField(default=0, verbose_name='Total invitations cliquées')),
                ('total_registrations', models.PositiveIntegerField(default=0, verbose_name='Total inscriptions')),
                ('total_rewards_given', models.PositiveIntegerField(default=0, verbose_name='Total récompenses données')),
                ('open_rate', models.FloatField(default=0, verbose_name="Taux d'ouverture")),
                ('click_rate', models.FloatField(default=0, verbose_name='Taux de clic')),
                ('registration_rate', models.FloatField(default=0, verbose_name="Taux d'inscription")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='referrals.referralprogram', verbose_name='Programme')),
            ],
            options={
                'verbose_name': 'Analytics de recommandation',
                'verbose_name_plural': 'Analytics de recommandation',
                'ordering': ['-date'],
                'unique_together': {('program', 'date')},
            },
        ),
    ]
