# Generated by Django 5.2.6 on 2025-09-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('candidate', 'Candidat'), ('admin', 'Administrateur'), ('hr', 'Ressources Humaines')], default='candidate', max_length=20),
        ),
    ]
