services:
  - type: web
    name: recruitment-platform
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn recruitment_platform.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      - key: REDIS_URL
        fromSecret: REDIS_URL
      - key: PYTHON_VERSION
        value: 3.11.6
    autoDeploy: true