services:
  - type: web
    name: recruitment-platform
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn --config gunicorn.conf.py --bind 0.0.0.0:$PORT recruitment_platform.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: neondb
          property: connectionString
      - key: CELERY_TASK_ALWAYS_EAGER
        value: true