# Generated by Django 4.2.7 on 2025-09-18 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Catégorie d'emploi",
                'verbose_name_plural': "Catégories d'emploi",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('job_type', models.CharField(blank=True, choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('contract', 'Contrat'), ('cdd', 'CDD'), ('cdi', 'CDI'), ('freelance', 'Freelance'), ('internship', 'Stage'), ('temporary', 'Temporaire'), ('apprenticeship', 'Apprentissage'), ('volunteer', 'Bénévolat'), ('seasonal', 'Saisonnier')], max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Débutant (0-2 ans)'), ('junior', 'Junior (2-5 ans)'), ('mid', 'Intermédiaire (5-8 ans)'), ('senior', 'Senior (8+ ans)'), ('lead', 'Lead/Manager'), ('principal', 'Principal'), ('director', 'Directeur'), ('executive', 'Exécutif'), ('c_level', 'C-Level')], max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remote_work', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email_frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='weekly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte emploi',
                'verbose_name_plural': 'Alertes emploi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('company_size', models.CharField(blank=True, choices=[('startup', 'Startup (1-10)'), ('small', 'Petite (11-50)'), ('medium', 'Moyenne (51-200)'), ('large', 'Grande (201-1000)'), ('enterprise', 'Entreprise (1000+)')], max_length=20)),
                ('company_description', models.TextField(blank=True)),
                ('company_website', models.URLField(blank=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('job_type', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('contract', 'Contrat'), ('cdd', 'CDD'), ('cdi', 'CDI'), ('freelance', 'Freelance'), ('internship', 'Stage'), ('temporary', 'Temporaire'), ('apprenticeship', 'Apprentissage'), ('volunteer', 'Bénévolat'), ('seasonal', 'Saisonnier')], max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Débutant (0-2 ans)'), ('junior', 'Junior (2-5 ans)'), ('mid', 'Intermédiaire (5-8 ans)'), ('senior', 'Senior (8+ ans)'), ('lead', 'Lead/Manager'), ('principal', 'Principal'), ('director', 'Directeur'), ('executive', 'Exécutif'), ('c_level', 'C-Level')], max_length=20)),
                ('work_environment', models.CharField(choices=[('office', 'Bureau'), ('remote', 'Télétravail'), ('hybrid', 'Hybride'), ('field', 'Terrain'), ('travel', 'Déplacements')], default='office', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('remote_work', models.BooleanField(default=False)),
                ('travel_required', models.BooleanField(default=False)),
                ('travel_percentage', models.PositiveIntegerField(blank=True, help_text='% de déplacements', null=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('responsibilities', models.TextField()),
                ('benefits', models.TextField(blank=True)),
                ('company_culture', models.TextField(blank=True)),
                ('growth_opportunities', models.TextField(blank=True)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('reports_to', models.CharField(blank=True, max_length=200)),
                ('manages_team', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='EUR', max_length=3)),
                ('salary_period', models.CharField(choices=[('hour', 'Par heure'), ('day', 'Par jour'), ('week', 'Par semaine'), ('month', 'Par mois'), ('year', 'Par an')], default='year', max_length=20)),
                ('salary_negotiable', models.BooleanField(default=True)),
                ('bonus_structure', models.TextField(blank=True)),
                ('equity_offered', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('paused', 'En pause'), ('closed', 'Fermé'), ('filled', 'Pourvu'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('confidential', models.BooleanField(default=False, help_text="Masquer le nom de l'entreprise")),
                ('interview_process', models.TextField(blank=True, help_text="Description du processus d'entretien")),
                ('number_of_positions', models.PositiveIntegerField(default=1)),
                ('application_questions', models.JSONField(blank=True, default=list, help_text='Questions personnalisées')),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('saves_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('assigned_recruiters', models.ManyToManyField(blank=True, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.jobcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emploi sauvegardé',
                'verbose_name_plural': 'Emplois sauvegardés',
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('required', 'Requis'), ('preferred', 'Souhaité'), ('nice_to_have', 'Un plus')], default='required', max_length=20)),
                ('years_required', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Compétence requise',
                'verbose_name_plural': 'Compétences requises',
                'unique_together': {('job', 'skill_name')},
            },
        ),
    ]
