# Generated by Django 5.2.6 on 2025-09-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'ordering': ['name'], 'verbose_name': "Catégorie d'emploi", 'verbose_name_plural': "Catégories d'emploi"},
        ),
        migrations.AlterModelOptions(
            name='jobskill',
            options={'verbose_name': 'Compétence requise', 'verbose_name_plural': 'Compétences requises'},
        ),
        migrations.AlterModelOptions(
            name='savedjob',
            options={'verbose_name': 'Emploi sauvegardé', 'verbose_name_plural': 'Emplois sauvegardés'},
        ),
        migrations.AlterField(
            model_name='job',
            name='application_questions',
            field=models.JSONField(blank=True, default=list, help_text='Questions personnalisées'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Débutant (0-2 ans)'), ('junior', 'Junior (2-5 ans)'), ('mid', 'Intermédiaire (5-8 ans)'), ('senior', 'Senior (8+ ans)'), ('lead', 'Lead/Manager'), ('principal', 'Principal'), ('director', 'Directeur'), ('executive', 'Exécutif'), ('c_level', 'C-Level')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('contract', 'Contrat'), ('cdd', 'CDD'), ('cdi', 'CDI'), ('freelance', 'Freelance'), ('internship', 'Stage'), ('temporary', 'Temporaire'), ('apprenticeship', 'Apprentissage'), ('volunteer', 'Bénévolat'), ('seasonal', 'Saisonnier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_period',
            field=models.CharField(choices=[('hour', 'Par heure'), ('day', 'Par jour'), ('week', 'Par semaine'), ('month', 'Par mois'), ('year', 'Par an')], default='year', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('paused', 'En pause'), ('closed', 'Fermé'), ('filled', 'Pourvu'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='travel_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='% de déplacements', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_environment',
            field=models.CharField(choices=[('office', 'Bureau'), ('remote', 'Télétravail'), ('hybrid', 'Hybride'), ('field', 'Terrain'), ('travel', 'Déplacements')], default='office', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Débutant (0-2 ans)'), ('junior', 'Junior (2-5 ans)'), ('mid', 'Intermédiaire (5-8 ans)'), ('senior', 'Senior (8+ ans)'), ('lead', 'Lead/Manager'), ('principal', 'Principal'), ('director', 'Directeur'), ('executive', 'Exécutif'), ('c_level', 'C-Level')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('contract', 'Contrat'), ('cdd', 'CDD'), ('cdi', 'CDI'), ('freelance', 'Freelance'), ('internship', 'Stage'), ('temporary', 'Temporaire'), ('apprenticeship', 'Apprentissage'), ('volunteer', 'Bénévolat'), ('seasonal', 'Saisonnier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='level',
            field=models.CharField(choices=[('required', 'Requis'), ('preferred', 'Souhaité'), ('nice_to_have', 'Un plus')], default='required', max_length=20),
        ),
    ]
