# Generated by Django 5.2.6 on 2025-10-01 20:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobcategory_options_alter_jobskill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
