# Generated by Django 5.2.6 on 2025-09-22 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Paramètres du site', 'verbose_name_plural': 'Paramètres du site'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'user__first_name'], 'verbose_name': "Membre d'équipe", 'verbose_name_plural': "Membres d'équipe"},
        ),
        migrations.AlterModelOptions(
            name='themesettings',
            options={'verbose_name': 'Thème', 'verbose_name_plural': 'Thèmes'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Valeur', 'verbose_name_plural': 'Valeurs'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publié le'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=200, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL, verbose_name='assigné à'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='répondu le'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='response',
            field=models.TextField(blank=True, verbose_name='réponse'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='new', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('general', 'Question générale'), ('technical', 'Problème technique'), ('account', 'Problème de compte'), ('job', 'Question sur une offre'), ('application', 'Question sur une candidature'), ('other', 'Autre')], max_length=20, verbose_name='sujet'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='réponse'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'Général'), ('account', 'Compte utilisateur'), ('jobs', "Offres d'emploi"), ('applications', 'Candidatures'), ('technical', 'Technique')], max_length=20, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='désinscrit le'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page_type',
            field=models.CharField(choices=[('about', 'À propos'), ('privacy', 'Politique de confidentialité'), ('terms', "Conditions d'utilisation"), ('faq', 'FAQ'), ('contact', 'Contact'), ('home', 'Accueil'), ('hero_section', 'Section héro'), ('footer_content', 'Contenu du footer'), ('career_tips', 'Conseils de carrière'), ('promotional', 'Contenu promotionnel'), ('custom', 'Page personnalisée')], max_length=20, verbose_name='type de page'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='modifié par'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_content',
            field=models.TextField(default="Recruitment Expert est une plateforme innovante de recrutement qui connecte les talents aux meilleures opportunités professionnelles. Fondée en 2020, notre mission est de révolutionner le marché de l'emploi grâce à une approche technologique et humaine.", verbose_name='contenu à propos'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_mission',
            field=models.TextField(default='Notre mission est de simplifier et optimiser le processus de recrutement en offrant une plateforme intuitive qui met en relation les meilleurs talents avec les entreprises qui partagent leurs valeurs et ambitions.', verbose_name='mission'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='À propos de Recruitment Expert', max_length=200, verbose_name='titre à propos'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_values',
            field=models.TextField(default='Innovation, Transparence, Excellence, Collaboration, Diversité', verbose_name='valeurs'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_vision',
            field=models.TextField(default='Devenir la référence en matière de plateforme de recrutement en Europe, en créant des connexions durables entre talents et entreprises.', verbose_name='vision'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='application_deadline_days',
            field=models.PositiveIntegerField(default=30, verbose_name='délai candidature (jours)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='auto_reject_after_days',
            field=models.PositiveIntegerField(default=90, help_text='Rejet automatique après X jours', verbose_name='rejet auto (jours)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='+33 1 23 45 67 89', max_length=20, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='danger_color',
            field=models.CharField(default='#dc3545', help_text='Couleur de danger (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_signature',
            field=models.TextField(default="L'équipe Recruitment Expert\nmohamedsaiddiallo88@gmail.com\n+33 6 28 53 09 45", verbose_name='signature email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(default='© 2024 Recruitment Expert. Tous droits réservés.', verbose_name='texte du footer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default="Découvrez des milliers d'opportunités d'emploi et connectez-vous avec les meilleures entreprises. Votre carrière commence ici.", verbose_name='sous-titre hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Trouvez votre emploi idéal', max_length=200, verbose_name='titre hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#007bff', help_text='Couleur principale (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#6c757d', help_text='Couleur secondaire (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(default='Plateforme complète de gestion de recrutement et de mise en relation talents-entreprises', verbose_name='description du site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='success_color',
            field=models.CharField(default='#28a745', help_text='Couleur de succès (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme_style',
            field=models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=20, verbose_name='style de thème'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='numéro de TVA'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='warning_color',
            field=models.CharField(default='#ffc107', help_text="Couleur d'avertissement (hex)", max_length=7),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon',
            field=models.CharField(help_text='Classe FontAwesome (ex: fas fa-users)', max_length=50, verbose_name='icône'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value',
            field=models.PositiveIntegerField(default=0, verbose_name='valeur'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('management', 'Direction'), ('technical', 'Technique'), ('hr', 'Ressources Humaines'), ('marketing', 'Marketing'), ('sales', 'Commercial'), ('support', 'Support'), ('other', 'Autre')], max_length=20, verbose_name='rôle'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='show_in_team',
            field=models.BooleanField(default=True, verbose_name="afficher dans l'équipe"),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='container_max_width',
            field=models.PositiveIntegerField(default=1200, help_text='Largeur max du container en px', verbose_name='largeur max container'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='custom_css',
            field=models.TextField(blank=True, help_text='CSS personnalisé', verbose_name='CSS personnalisé'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='danger_color',
            field=models.CharField(default='#dc3545', max_length=7, verbose_name='couleur danger'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='dark_color',
            field=models.CharField(default='#343a40', max_length=7, verbose_name='couleur sombre'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='info_color',
            field=models.CharField(default='#17a2b8', max_length=7, verbose_name='couleur info'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_color',
            field=models.CharField(default='#f8f9fa', max_length=7, verbose_name='couleur claire'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='couleur primaire'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='couleur secondaire'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='success_color',
            field=models.CharField(default='#28a745', max_length=7, verbose_name='couleur succès'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='warning_color',
            field=models.CharField(default='#ffc107', max_length=7, verbose_name='couleur avertissement'),
        ),
        migrations.AlterField(
            model_name='value',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='value',
            name='icon',
            field=models.CharField(help_text='Classe FontAwesome (ex: fas fa-heart)', max_length=50, verbose_name='icône'),
        ),
        migrations.AlterField(
            model_name='value',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
    ]
