# Generated by Django 4.2.7 on 2025-09-20 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Recruitment Expert SAS', max_length=200, verbose_name="nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rcs',
            field=models.CharField(blank=True, max_length=50, verbose_name='RCS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='siret',
            field=models.CharField(blank=True, max_length=14, verbose_name='SIRET'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='numéro de TVA'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, max_length=500, verbose_name='extrait'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='image principale'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='meta description'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='meta keywords'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publié le'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=200, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre de vues'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL, verbose_name='assigné à'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='répondu le'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='response',
            field=models.TextField(blank=True, verbose_name='réponse'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='new', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('general', 'Question générale'), ('technical', 'Problème technique'), ('account', 'Problème de compte'), ('job', 'Question sur une offre'), ('application', 'Question sur une candidature'), ('other', 'Autre')], max_length=20, verbose_name='sujet'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='réponse'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'Général'), ('account', 'Compte utilisateur'), ('jobs', "Offres d'emploi"), ('applications', 'Candidatures'), ('technical', 'Technique')], max_length=20, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='inscrit le'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='désinscrit le'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=models.TextField(verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='meta description'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='meta keywords'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page_type',
            field=models.CharField(choices=[('about', 'À propos'), ('privacy', 'Politique de confidentialité'), ('terms', "Conditions d'utilisation"), ('faq', 'FAQ'), ('contact', 'Contact'), ('home', 'Accueil'), ('hero_section', 'Section héro'), ('footer_content', 'Contenu du footer'), ('career_tips', 'Conseils de carrière'), ('promotional', 'Contenu promotionnel'), ('custom', 'Page personnalisée')], max_length=20, verbose_name='type de page'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name='afficher dans le menu'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='modifié par'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_content',
            field=models.TextField(default="Recruitment Expert est une plateforme innovante de recrutement qui connecte les talents aux meilleures opportunités professionnelles. Fondée en 2020, notre mission est de révolutionner le marché de l'emploi grâce à une approche technologique et humaine.", verbose_name='contenu à propos'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_mission',
            field=models.TextField(default='Notre mission est de simplifier et optimiser le processus de recrutement en offrant une plateforme intuitive qui met en relation les meilleurs talents avec les entreprises qui partagent leurs valeurs et ambitions.', verbose_name='mission'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='À propos de Recruitment Expert', max_length=200, verbose_name='titre à propos'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_values',
            field=models.TextField(default='Innovation, Transparence, Excellence, Collaboration, Diversité', verbose_name='valeurs'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_vision',
            field=models.TextField(default='Devenir la référence en matière de plateforme de recrutement en Europe, en créant des connexions durables entre talents et entreprises.', verbose_name='vision'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(default='123 Avenue des Entreprises\n75001 Paris, France', verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='admin_notification_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email admin'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='application_deadline_days',
            field=models.PositiveIntegerField(default=30, verbose_name='délai candidature (jours)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='auto_reject_after_days',
            field=models.PositiveIntegerField(default=90, help_text='Rejet automatique après X jours', verbose_name='rejet auto (jours)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='contact@recruitment-expert.com', max_length=254, verbose_name='email de contact'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='+33 1 23 45 67 89', max_length=20, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='notifications email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_signature',
            field=models.TextField(default="L'équipe Recruitment Expert\ncontact@recruitment-expert.com\n+33 1 23 45 67 89", verbose_name='signature email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_auto_matching',
            field=models.BooleanField(default=True, verbose_name='matching automatique'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_tracking',
            field=models.BooleanField(default=False, verbose_name='suivi analytics'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(default='© 2024 Recruitment Expert. Tous droits réservés.', verbose_name='texte du footer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID Google Analytics'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='image hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default="Découvrez des milliers d'opportunités d'emploi et connectez-vous avec les meilleures entreprises. Votre carrière commence ici.", verbose_name='sous-titre hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Trouvez votre emploi idéal', max_length=200, verbose_name='titre hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(blank=True, verbose_name='message maintenance'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='mode maintenance'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='matching_threshold',
            field=models.PositiveIntegerField(default=70, help_text='Seuil de matching en %', verbose_name='seuil matching'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='max_applications_per_day',
            field=models.PositiveIntegerField(default=5, verbose_name='max candidatures/jour'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='show_social_links',
            field=models.BooleanField(default=True, verbose_name='afficher liens sociaux'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(default='Plateforme complète de gestion de recrutement et de mise en relation talents-entreprises', verbose_name='description du site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Plateforme de Recrutement Expert', max_length=100, verbose_name='nom du site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme_style',
            field=models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=20, verbose_name='style de thème'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon',
            field=models.CharField(help_text='Classe FontAwesome (ex: fas fa-users)', max_length=50, verbose_name='icône'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='title',
            field=models.CharField(max_length=100, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value',
            field=models.PositiveIntegerField(default=0, verbose_name='valeur'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, verbose_name='biographie'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('management', 'Direction'), ('technical', 'Technique'), ('hr', 'Ressources Humaines'), ('marketing', 'Marketing'), ('sales', 'Commercial'), ('support', 'Support'), ('other', 'Autre')], max_length=20, verbose_name='rôle'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='show_in_team',
            field=models.BooleanField(default=True, verbose_name="afficher dans l'équipe"),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='border_radius',
            field=models.PositiveIntegerField(default=6, help_text='Rayon des bordures en px', verbose_name='rayon bordures'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='container_max_width',
            field=models.PositiveIntegerField(default=1200, help_text='Largeur max du container en px', verbose_name='largeur max container'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='custom_css',
            field=models.TextField(blank=True, help_text='CSS personnalisé', verbose_name='CSS personnalisé'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='danger_color',
            field=models.CharField(default='#dc3545', max_length=7, verbose_name='couleur danger'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='dark_color',
            field=models.CharField(default='#343a40', max_length=7, verbose_name='couleur sombre'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='font_family',
            field=models.CharField(default='Segoe UI, system-ui, sans-serif', max_length=100, verbose_name='police'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='font_size_base',
            field=models.PositiveIntegerField(default=16, help_text='Taille de police de base en px', verbose_name='taille police base'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='info_color',
            field=models.CharField(default='#17a2b8', max_length=7, verbose_name='couleur info'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_color',
            field=models.CharField(default='#f8f9fa', max_length=7, verbose_name='couleur claire'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='couleur primaire'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='couleur secondaire'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='success_color',
            field=models.CharField(default='#28a745', max_length=7, verbose_name='couleur succès'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='warning_color',
            field=models.CharField(default='#ffc107', max_length=7, verbose_name='couleur avertissement'),
        ),
        migrations.AlterField(
            model_name='value',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='value',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='value',
            name='icon',
            field=models.CharField(help_text='Classe FontAwesome (ex: fas fa-heart)', max_length=50, verbose_name='icône'),
        ),
        migrations.AlterField(
            model_name='value',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='value',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='value',
            name='title',
            field=models.CharField(max_length=100, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='value',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
    ]
