# Generated by Django 4.2.7 on 2025-09-18 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('shortlisted', 'Présélectionné'), ('interview_scheduled', 'Entretien programmé'), ('interview_completed', 'Entretien terminé'), ('offer_made', 'Offre faite'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('withdrawn', 'Retiré')], default='pending', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('cover_letter', models.TextField()),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='applications/resumes/')),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='applications/documents/')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('custom_answers', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-applied_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Téléphonique'), ('video', 'Visioconférence'), ('in_person', 'En personne'), ('technical', 'Technique'), ('panel', 'Panel')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Programmé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('rescheduled', 'Reprogrammé')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('overall_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('hire', "Recommande l'embauche"), ('maybe', 'Mitigé'), ('no_hire', 'Ne recommande pas')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL)),
                ('interviewers', models.ManyToManyField(related_name='conducted_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entretien',
                'verbose_name_plural': 'Entretiens',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('shortlisted', 'Présélectionné'), ('interview_scheduled', 'Entretien programmé'), ('interview_completed', 'Entretien terminé'), ('offer_made', 'Offre faite'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('withdrawn', 'Retiré')], max_length=30)),
                ('new_status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('shortlisted', 'Présélectionné'), ('interview_scheduled', 'Entretien programmé'), ('interview_completed', 'Entretien terminé'), ('offer_made', 'Offre faite'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('withdrawn', 'Retiré')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('resume', 'CV'), ('cover_letter', 'Lettre de motivation'), ('portfolio', 'Portfolio'), ('certificate', 'Certificat'), ('reference', 'Lettre de recommandation'), ('other', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='applications/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document de candidature',
                'verbose_name_plural': 'Documents de candidature',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('general', 'Général'), ('screening', 'Présélection'), ('interview', 'Entretien'), ('reference', 'Référence'), ('decision', 'Décision')], default='general', max_length=20)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='applications.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(choices=[('experience', 'Expérience'), ('skills', 'Compétences'), ('education', 'Formation'), ('motivation', 'Motivation'), ('cultural_fit', 'Adéquation culturelle'), ('communication', 'Communication'), ('overall', 'Évaluation globale')], max_length=20)),
                ('score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField(default=5)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='applications.application')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'unique_together': {('application', 'evaluator', 'criteria')},
            },
        ),
    ]
