# Generated by Django 5.2.6 on 2025-10-01 20:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='additional_documents',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw'),
        ),
    ]
