# Generated by Django 5.2.6 on 2025-10-06 14:23

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_additional_documents_and_more'),
        ('jobs', '0003_job_job_description_file_alter_job_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='presentation_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='application',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Durée en secondes', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='video_questions',
            field=models.JSONField(blank=True, default=list, help_text='Questions posées dans la vidéo'),
        ),
        migrations.AddField(
            model_name='application',
            name='video_transcript',
            field=models.TextField(blank=True, help_text='Transcription automatique de la vidéo'),
        ),
        migrations.CreateModel(
            name='VideoApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('question_responses', models.JSONField(default=list, help_text='Réponses aux questions vidéo')),
                ('total_duration', models.PositiveIntegerField(help_text='Durée totale en secondes')),
                ('video_quality', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('ultra', 'Ultra')], default='medium', max_length=20)),
                ('transcript', models.TextField(blank=True)),
                ('keywords_extracted', models.JSONField(blank=True, default=list)),
                ('sentiment_analysis', models.JSONField(blank=True, default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_application', to='applications.application')),
            ],
            options={
                'verbose_name': 'Candidature vidéo',
                'verbose_name_plural': 'Candidatures vidéo',
            },
        ),
        migrations.CreateModel(
            name='VideoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('introduction', 'Présentation personnelle'), ('motivation', 'Motivation pour le poste'), ('experience', 'Expérience pertinente'), ('skills', 'Compétences techniques'), ('challenge', 'Défi professionnel'), ('goals', 'Objectifs de carrière'), ('custom', 'Question personnalisée')], max_length=20)),
                ('question_text', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('time_limit', models.PositiveIntegerField(default=120, help_text='Temps limite en secondes')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_questions', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Question vidéo',
                'verbose_name_plural': 'Questions vidéo',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
